site_name: Black Eyes and Broken Souls
site_author: Paul Green
site_description: >-
  A repository for the lore and character details for the
  Mick Hargraves series of novels.
repo_name: MickHargraves
repo_url: https://github.com/warlord0/MickHargraves
docs_dir: notes
theme:
  logo: assets/logo.svg
  favicon: assets/favicon.png
  name: material
  features:
    - search.suggest
    - navigation.footer
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.path
    - navigation.top
    - toc.follow
  palette:
    - media: (prefers-color-scheme)
      toggle:
        icon: material/lightbulb-variant
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red
      accent: red
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/lightbulb-multiple-outline
        name: Switch to system preference
plugins:
  - search
  - meta
  - offline
  - tags
  - minify:
      minify_html: true
copyright: Copyright &copy; 2025, Paul Green
watch:
  - includes
extra:
  generator: false
markdown_extensions:
  - abbr
  - admonition
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md