site_name: Black Eyes and Broken Souls
site_author: Paul Green
site_description: >-
  A repository for the lore and character details for the
  Mick Hargraves series of novels.
repo_name: Mick Hargraves
repo_url: https://github.com/warlord0/MickHargraves
docs_dir: notes
theme:
  icon:
    repo: fontawesome/brands/git-alt
  logo: assets/logo.svg
  favicon: assets/favicon.png
  name: material
  features:
    - header.autohide
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.path
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.suggest
    - toc.follow
  palette:
    - media: (prefers-color-scheme)
      toggle:
        icon: material/lightbulb-variant
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red
      accent: red
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/lightbulb-multiple-outline
        name: Switch to system preference
plugins:
  - search
  - meta
  - offline
  - tags
  - minify:
      minify_html: true
  - backlinks_section:
      # ignore_links_from:
      #   - index.md
      # ignore_links_to:
      #   - index.md
      add_to_toc: false
      hide_if_empty: true
copyright: Black Eyes and Broken Souls © 2024 by Paul Green is licensed under CC BY-NC-SA 4.0. To view a copy of this license, visit https://creativecommons.org/licenses/by-nc-sa/4.0/
watch:
  - includes
extra:
  generator: false
  social:
    - icon: fontawesome/solid/certificate
      link: https://creativecommons.org/licenses/by-nc-sa/4.0/
      name: License CC BY-NC-SA 4.0
markdown_extensions:
  - abbr
  - admonition
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
