services:
  docusaurus:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./website:/app/website:rw
    environment:
      - NODE_ENV=development
    command: [ "npm", "start" ]
    # Keep the container running even if the command fails
    restart: on-failure
